title: G M Arafat Rahman
logo: /images/arafat portfolio pic.jpg
description: Erasmus Mundus Scholar

            :Charles University in Prague, Czech Republic and University of Lorraine, France
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
