title: <p align="center"> G M Arafat Rahman </p>
logo: 
  <p align="center">
  <img src="images/portfolio_pic.jpg" alt="Arafat Rahman" style="width:150px;height:150px;border-radius:50%;">
  </p>
description: 
             <p align="center">
              Erasmus Mundus Scholar
              <br> Charles University in Prague, Czech Republic and University of Lorraine, France
              <br> g.m.arafat.rahman@outlook.com
              
              <a href="https://www.linkedin.com/in/g-m-arafat-rahman/">LinkedIn</a> |
              <a href="https://github.com/arafat04">GitHub</a>
            
              </p>
              
              <p align="justify">
              I am currently pursuing master's degree in Computational Linguistics and Natural language processing under Erasmus Mundus <b>Language and Communications Technologies(LCT)</b>.
            
              </p>

theme: jekyll-theme-minimal
